# Site settings
title: Sean Blanda
email: scblanda@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sean Blanda is the Director and Editor-in-Chief of 99U. He lives in New York City.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://seanblanda.com" # the base hostname & protocol for your site
twitter_username: seanblanda
github_username:  blandanomics
# Build settings
markdown: kramdown
image: "/images/"
